from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import csv
import fractions
import json
import os


def login(driver):
    import secrets
    driver.get('https://cronometer.com/login/')
    user_ele = driver.find_element_by_name('username')
    pass_ele = driver.find_element_by_name('password')
    user_ele.send_keys(secrets.u)
    pass_ele.send_keys(secrets.p)

    submit_button = driver.find_element_by_id('login-button')
    submit_button.click()


def robust_click(element, driver):
    """
    Sometimes the "Subscribe to Cronometer Gold" dialog pops up, which can
    block a Selenium mouse click. If this will close that dialog before trying
    to click the given element.
    """
    element.click()
    # TODO once we get the modal, refactor the following code to not use
    # autogenerated class names.
    # try:
        # element.click()
    # except ElementClickInterceptedException:
        # # close dialog
        # cancel_button = driver.find_element_by_class_name('GHDCC5OBEIC')
        # cancel_button.click()
        # print('Closed subscription popup dialog!')

        # # retry clicking the element
        # element.click()


# def add_recipe_to_diary(driver, recipe_props):
    # is_favorite = recipe_props['is_favorite']

    # # Click add to diary
    # if is_favorite:
        # print(recipe_props['name'])
        # add_to_diary_button = driver.find_element_by_class_name('GHDCC5OBKN')
        # robust_click(add_to_diary_button, driver)
        # try:
            # # Wait for add modal to show
            # WebDriverWait(driver, WAIT_SECONDS).until(
                # EC.presence_of_element_located((
                    # By.CLASS_NAME,
                    # 'btn-orange-flat'))
            # )
            # # Add recipe
            # add_recipe_button = driver.find_element_by_class_name(
                # 'btn-orange-flat')
            # robust_click(add_recipe_button, driver)
        # except TimeoutException:
            # print('The "add to diary" modal took too long to load.')
    # return 0


# TODO reimplement this
# def add_starred_recipes_to_diary():
    # # Enable headless Firefox
    # os.environ['MOZ_HEADLESS'] = '1'

    # print('Adding favorite/starred recipes to today\'s diary entry...')
    # with webdriver.Firefox(executable_path='./geckodriver') as driver:
        # login(driver)
        # iterate_over_recipes(driver, add_recipe_to_diary)
    # print()
